### ISSUE TITLE
UX/Interface for Orbit Tracker

### ISSUE THREAD

**Issue by aaroncameron21** [orbitable/bridge#104]
UX for Orbit Tracker should include functionality to:
- [ ] Select 'center' body
- [ ] Select 'target' body
- [ ] Initiate tracking
- [ ] View # of orbits completed
- [ ] View average orbital period
- [ ] Stop tracking
